#!/usr/bin/env python3
"""
Utility script to inspect the ChromaDB index produced by the pipeline.

Examples:
    python check.py                  # List all collections with counts
    python check.py --collection foo # Inspect a specific collection
    python check.py --limit 3 --show-metadata
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

try:
    import chromadb
except ModuleNotFoundError as exc:
    raise SystemExit(
        "Missing dependency 'chromadb'. Install it with 'pip install chromadb' and retry."
    ) from exc


DEFAULT_INDEX_DIR = Path("output") / "vector_index"
DEFAULT_COLLECTION = os.environ.get("VECTOR_COLLECTION", "manual_chunks")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Inspect the ChromaDB persistent store generated by the pipeline."
    )
    parser.add_argument(
        "--index-dir",
        type=Path,
        default=DEFAULT_INDEX_DIR,
        help="Path to the ChromaDB persistent directory (default: output/vector_index).",
    )
    parser.add_argument(
        "--collection",
        type=str,
        default=None,
        help="Collection name to inspect. Defaults to VECTOR_COLLECTION env var or 'manual_chunks'.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=5,
        help="Number of sample documents to display when inspecting a collection.",
    )
    parser.add_argument(
        "--show-metadata",
        action="store_true",
        help="Display metadata for each sampled document.",
    )
    return parser.parse_args()


def require_index_dir(path: Path) -> None:
    if not path.exists():
        raise SystemExit(f"Index directory not found: {path}")
    if not path.is_dir():
        raise SystemExit(f"Index path is not a directory: {path}")


def list_collections(client: chromadb.PersistentClient) -> None:
    collections = client.list_collections()
    if not collections:
        print("No collections found in the index.")
        return

    print("Collections in persistent store:")
    for collection in collections:
        coll = client.get_collection(collection.name)
        print(f"  • {collection.name}: {coll.count()} documents")


def inspect_collection(
    client: chromadb.PersistentClient,
    collection_name: str,
    limit: int,
    show_metadata: bool,
) -> None:
    try:
        collection = client.get_collection(collection_name)
    except Exception as exc:
        raise SystemExit(f"Failed to load collection '{collection_name}': {exc}") from exc

    total = collection.count()
    print(f"\nCollection '{collection_name}' contains {total} documents.")
    if total == 0 or limit <= 0:
        return

    sample = collection.get(limit=min(limit, total))
    ids = sample.get("ids", [])
    documents = sample.get("documents", [])
    metadatas = sample.get("metadatas", [])

    print(f"Showing up to {len(ids)} sample document(s):")
    for idx, doc_id in enumerate(ids):
        snippet = documents[idx][:200].replace("\n", " ")
        print(f"\n[{idx + 1}] {doc_id}")
        print(f"    Text: {snippet}{'...' if len(documents[idx]) > 200 else ''}")
        if show_metadata:
            metadata = metadatas[idx] or {}
            if metadata:
                print("    Metadata:")
                for key, value in metadata.items():
                    print(f"      - {key}: {value}")
            else:
                print("    Metadata: <empty>")


def main() -> None:
    args = parse_args()
    index_dir = args.index_dir.resolve()
    require_index_dir(index_dir)

    client = chromadb.PersistentClient(path=str(index_dir))
    list_collections(client)

    collection_name = args.collection or DEFAULT_COLLECTION
    if collection_name:
        inspect_collection(client, collection_name, args.limit, args.show_metadata)


if __name__ == "__main__":
    main()

